# Generated by Django 4.2.2 on 2023-12-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_five',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_four',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_three',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_two',
            field=models.TextField(blank=True),
        ),
    ]
