# Generated by Django 4.2.2 on 2023-12-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_content_five_post_content_four_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mix',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
